title: Gallery KANKAN
description: Gallery KANKAN

url: http://gallerykankan.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Collections
   url: /collections.html
 - title: Links
   url: /links.html

social:
   email: honten@kankan.co.jp

